### ISSUE TITLE
A neo-tree issue I do not understand

### ISSUE THREAD

**Issue by windowsrefund** [ramojus/mellifluous.nvim#21]
Greetings. Thank you for this great theme. Hoping someone can help me understand how to overcome this issue or explain why certain text is black?

![neo-tree](https://github.com/ramojus/mellifluous.nvim/assets/512222/681ceb81-4c97-4d8a-99c8-5eceda4ebefa)

Happy to provide additional details as needed.

**Comment by ramojus** [comment]
Hello, this is an issue on the part of the colorscheme. Neo-tree highlights should be updated. I personally use NvimTree, so the highlights are usually good for that plugin, as I will make an update pretty quickly if something needs to changed. But this is not difficult, so I might do it this week.

In the meantime you're welcome to submit a PR. Neo-tree highlight groups can be checked with `:h neo-tree-highlights`. The highlights that this colorscheme sets can be checked and should be updated [here](https://github.com/ramojus/mellifluous.nvim/blob/main/lua/mellifluous/highlights/plugins/neo_tree.lua).
I can also see that the white (indent or subfolder) lines don't look good in the screenshot that you have provided, so that should probably also be updated.

**Comment by LennyLizowzskiy** [comment]
Same issue when using kanagawa_dragon colorset

![image](https://github.com/ramojus/mellifluous.nvim/assets/46971551/96aa7706-c995-4b20-814f-6790501ba439)

**Comment by ramojus** [comment]
Fixed. Feel free to let me know if there are some issues still.

@LennyLizowzskiy all of the color sets are using the same highlight rules, so an issue with highlights when using one color set is normally an issue when using any of them.

**Comment by LennyLizowzskiy** [comment]
@ramojus thanks. Cool colorscheme tho. I've tried so many of them (also in VSCode and IDEA) and used github-dark-dimmed before but your colorschemes are really top notch. Minimalistic yet very informative without rainbow bursts or any other distractions

**Comment by ramojus** [comment]
> without rainbow bursts

Wait until you see headings in markdown (using treesitter) :D (I really wanted them to stand out, still not sure about my solution, so it may change)

But thanks a lot for the good words, minimalistic yet informative was the goal.
