### ISSUE TITLE
Please consider adding hierline support

### ISSUE THREAD

**Issue by windowsrefund** [ramojus/mellifluous.nvim#25]
I'd PR it myself but I can't figure out what [this is suggesting](https://github.com/rebelot/heirline.nvim/blob/master/cookbook.md#theming)

**Comment by ramojus** [comment]
Heirline is a DYI type of plugin, where you have to define everything yourself, but with a bunch of provided utilities. So it has no highlight groups. They are suggesting to just use the existing highlights that are normally used for highlighting similar things within neovim. If you use astronvim, it seems like [this](https://github.com/AstroNvim/AstroNvim/blob/main/lua/astronvim/plugins/_astroui_status.lua#L127) is where they define the highlights they use for heirline. This colorscheme might be missing some (pretty sure WinBar is missing, it should be added at some point), so you can have a look if you want to.
Also it seems like they have some sort of `Heirline*` highlights going on, but I would like to avoid those, if possible, because I wouldn't want for this colorscheme to support specific neovim configurations.

**Comment by windowsrefund** [comment]
Thank you for the explanation. I'll dig in based off your comment.
