### ISSUE TITLE
Must set other color scheme before I can set mellifluous as my color scheme

### ISSUE THREAD

**Issue by rathod-sahaab** [ramojus/mellifluous.nvim#5]
```lua
require('impatient')
require('rathod-sahaab')

require 'mellifluous'.setup({
  -- default conf
})

-- setting this is required before mellifluous or else nothing works
vim.cmd("colorscheme gruvbox")
vim.cmd("colorscheme mellifluous")
```

Even manually calling `:colorscheme mellifluous`  does not work unless I set different color scheme first

**Comment by ramojus** [comment]
Thanks for making this issue!

I think this happens due to `vim.opt.termguicolors` not being set (most people set this in their configs). This makes neovim think that your terminal doesn't support [24-bit true colors](https://github.com/termstandard/colors) and this support is required for mellifluous.

It should be fixed now, but in the future I would recommend having `vim.opt.termguicolors = true` line in your config, otherwise a lot of colorschemes will show different colors.

Let me know if its working for you.

**Comment by rathod-sahaab** [comment]
Hi, @ramojus that was exactly what the problem was I might have purged that line while changing themes, Thanks for the awesome theme!
