### ISSUE TITLE
Trying to override highlights for a plugin

### ISSUE THREAD

**Issue by windowsrefund** [ramojus/mellifluous.nvim#64]
Hello again,

Trying to take advantage of the information [here](https://github.com/refractalize/oil-git-status.nvim/tree/main#highlight-groups) but  the following is not working. Any help would be greatly appreciated:

```
    opts = {
      highlight_overrides = {
        dark = function(hl, colors)
          hl.set("SignColumn", { bg = colors.bg })
          hl.set("Directory", { fg = colors.ui_blue })
          for _, hl_group in pairs(require("oil-git-status").highlight_groups) do
            hl.set(hl_group, { bg = colors.bg })
          end
        end,
      },
   }
```

I'm obviously committing some crime against Lua by adding that `for` loop in there like that.

**Comment by ramojus** [comment]
What exactly is not working? I've tried your use your snippet, and changing the highlights seem to work just fine (without the for loop, because I don't use "oil-git-status").

The `for` loop for "oil-git-status" is a separate issue. Buuut I checked it briefly and I noticed that you did not specify the field on `nvim_set_hl` line: (taken from plugin documentation)
```
vim.api.nvim_set_hl(0, hl_group.hl_group, { fg = "#ff0000" })
```
So it should be `hl_group.hl_group`.

**Comment by windowsrefund** [comment]
Thanks for the help. A bit of trial and error got it working with the following:

```
      highlight_overrides = {
        dark = function(hl, colors)
          hl.set("SignColumn", { bg = colors.bg })
          hl.set("Directory", { fg = colors.ui_blue })
          for _, hl_group in pairs(require("oil-git-status").highlight_groups) do
            hl.set(hl_group.hl_group, { bg = colors.bg })
          end
        end,
      },
```
